FROM ubuntu:20.04

# Update package list
RUN apt-get update

# Install nginx
RUN apt-get install -y nginx

# Install curl for testing
RUN apt-get install -y curl
RUN apt-get install vim -y
RUN apt-get clean
RUN rm /var/www/html/index.nginx-debian.html
COPY index.html /var/www/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
