FROM node:16-alpine AS builder
WORKDIR /app
#copy package file
COPY package*.json ./
#install dependenceis
RUN npm install --only=production
#prodeuction stage
FROM node:16-alpine AS production
WORKDIR /app

#copy only required files
COPY --from=builder /app/node_modules ./node_modules

COPY package*.json ./
COPY server.js ./
COPY index.html ./

#create non root user
RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001
USER nodejs
EXPOSE 3000
CMD ["npm", "start"]
