FROM ubuntu:20.04
#update packege
RUN apt-get update
#install nginx
RUN apt-get install nginx -y 
RUN apt-get install curl -y 
#install vim 
RUN apt-get install -y vim
RUN apt-get clean
RUN rm /var/www/html/index.nginx-debian.html
COPY index.html /var/www/htm/
EXPOSE 80
 #commands
CMD ["nginx", "-g","daemon off;"]
